In [ ]:
# 0.2 
# added descriptions
# added dictionary + load and save functions
# added sorting function
# new cols for months and category
# basic export

In [3]:
import pandas as pd
import re
import time
import pickle
import csv

#just a basic sum function for the table - throw out?
def findsum(word = '', df = fin,col = 'desc', figcol = 'figure'):
    total = df.loc[df[col].str.contains(word, flags=re.I, regex=True, na = False)][figcol].sum()
    return total

NameError: name 'fin' is not defined

In [5]:
#reads excel file

fin = pd.read_excel('skandia_2020-01-01_2020-01-01.xlsx')

In [32]:
#cleans input

fin.columns = fin.iloc[2]
fin = fin.drop([0,1,2])
fin = fin.reset_index()
fin = fin.drop(columns = 'index')

In [33]:
#renames and cleans further

fin.columns = ['date', 'desc', 'figure', 'balance']
fin.loc[fin['desc'].str.contains('^2020|^2019', 
                                 flags = re.I, 
                                 regex = True, 
                                 na = False), 
        'desc'] = fin['desc'].str.slice(start = 10)
fin

,date,desc,figure,balance
0,2020-05-04,"NETONNET AB, VÄXJÖ",-539,25556.7
1,2020-05-04,"NETONNET AB, VÄXJÖ",-200,26095.7
2,2020-04-30,"VAXJO OAS CAFE, VAXJO",-98,26295.7
3,2020-04-30,"PRESSBYRÅN 4025376, VÄXJÖ",-70,26393.7
4,2020-04-30,"kontaktlös LIDL 131/VEXJO OSTERLEDEN, VEXJO",-41.7,26463.7
...,...,...,...,...
225,2020-01-02,"WILLYS VÄXJÖ I11, VÄXJÖ",-1200.41,25103.3
226,2020-01-02,"SYSTEMBOLAGET VÄXJÖ, VÄXJÖ",-393,26303.7
227,2020-01-02,"WILLYS VÄXJÖ I11, VÄXJÖ",-23.8,26696.7
228,2020-01-02,"JULA AB, VÄXJÖ",-199,26720.5
229,2020-01-02,"BILTEMA SWEDEN VEXJO, VEXJO",-474.6,26919.5

In [5]:
# dictionary with categories and keywords

fincat = {'literature': [], 
          'revolut': ['REVOLUT'], 
          'charity': [],
          'utilities': [], 
          'alcohol': ['SYSTEMBOLAGET'], 
          'holidays': [], 
          'gifts': [], 
          'furniture': [], 
          'tools': [], 
          'electro': [], 
          'phone': [], 
          'rent': [], 
          'car': [], 
          'food': ['WILLYS', 'LIDL', 'PRESSBYRÅN', 'MAX'], 
          'transportation': [], 
          'trips_home': [], 
          'clothes': [], 
          'freetime': [], 
          'exercise': [], 
          'health': [], 
          'savings': [], 
          'misc': [],
          'salary' : []}

fincat_desc = {'literature': '', 'revolut': '', 'charity': '', 'utilities': '', 'alcohol': '', 'holidays': '', 'gifts': '', 
          'furniture': '', 'tools': '', 'electro': '', 'phone': '', 'rent': '', 'car': '', 'food': '', 'transportation': '', 
          'trips_home': '', 'clothes': '', 'freetime': '', 'exercise': '', 'health': '', 'savings': '', 'misc': ''}

In [4]:
with open('fincat.csv', 'w') as csvfile:
    writer = csv.writer(csvfile)
    for key, value in fincat.items():
        writer.writerow([key, value])

In [10]:
# saving and loading the dict

with open('fincat.dict', 'wb') as fincat_file:
    pickle.dump(fincat, fincat_file)

with open('fincat.dict', 'rb') as fincat_file:
    fincat = pickle.load(fincat_file)
    print(fincat)

{'misc': [], 'rent': [], 'tools': [], 'charity': [], 'alcohol': ['SYSTEMBOLAGET'], 'savings': [], 'health': [], 'electro': [], 'exercise': [], 'literature': [], 'transportation': [], 'food': ['WILLYS', 'LIDL', 'PRESSBYR\xc3\x85N', 'MAX'], 'utilities': [], 'holidays': [], 'gifts': [], 'phone': [], 'freetime': [], 'furniture': [], 'L\xc3\x96N': [], 'car': [], 'trips_home': [], 'revolut': ['REVOLUT'], 'clothes': []}

In [11]:
# search and categorize function 
# can even handle adding keywords to the list

# TODO: add a prefill functionality to the input function - in matplotlib?
#      add a category input and ability to acces and add to dict - choose from a list interface
#      package to a function
#      remove .drop and instead make a new col with categories
#      ignore capitalization
#      replace str.find with re.search


words = ['WILLYS', 'LIDL', 'JULA', 'PRESSBYRÅN', 'NETONNET', 'SYSTEMBOLAGET', 'BILTEMA', 'MAX']
altfin = fin
match = 0
newkey = '#################'

for i, row in altfin.iterrows():
#    input('Waiting...Please press Enter')
#    print(row['desc'])
    
    for w, key in enumerate(words):
#        print(key)
#        print(str(row['desc']).find(key) != -1)
#        time.sleep(0.3)
            
        if str(row['desc']).find(key) != -1:
            match += 1
            altfin = altfin.drop(index = i)
            break
        
        elif (w >= len(words) - 1) & (newkey == ''):
            break
        
        elif w >= len(words) - 1:
#            print(row['desc'])
            newkey = input('Input new keyword:')
#            category = input('Define category:')
            if newkey == '':
                break
            else:
                words.append(newkey)
        
print ('Matches: ' + str(match))
print (altfin)
print (words)

 VAXJO OAS CAFE, VAXJO
Enter new keyword:
Matches: 64
           date                               desc  figure  balance
2    2020-04-30              VAXJO OAS CAFE, VAXJO     -98  26295.7
5    2020-04-30             BURGER KING AVD, VÄXJÖ     -87  26505.4
6    2020-04-30              Autogiro CA ARABYBOST   -9012  26592.4
7    2020-04-30            Överföring 9159 8807910    -500  35604.4
8    2020-04-28       ICA SUPERMARKET DALBO, VAXJO -222.87  36104.4
..          ...                                ...     ...      ...
217  2020-01-03        BONAN OCH MUSTASCHEN, VAXJO     -78  22329.7
218  2020-01-03   Klarna * spelexperten.com, Gavle    -388  22407.7
219  2020-01-02                   ST1 VÄXJÖ, VÄXJÖ -242.54  22795.7
221  2020-01-02             XXL SPORT & VIL, VÄXJÖ   -1946  22819.4
224  2020-01-02      CONDECO STORGATAN VEXJ, VEXJO    -294  24809.3

[166 rows x 4 columns]
['WILLYS', 'LIDL', 'JULA', 'PRESSBYRÅN', 'NETONNET', 'SYSTEMBOLAGET', 'BILTEMA', 'MAX']

In [38]:
# creating the new cols for months and categories

# CREATE
fin['category'] = 'NaN'

# CREATE by split
fin['month'] = fin['date'].str.split('-', expand = True)[1]

# REARRANGE
cols = list(fin.columns)
fin = fin[[cols[0]] + [cols[-1]] + cols[1:-1]]

fin

,date,month,desc,figure,balance,category
0,2020-05-04,05,"NETONNET AB, VÄXJÖ",-539,25556.7,NaN
1,2020-05-04,05,"NETONNET AB, VÄXJÖ",-200,26095.7,NaN
2,2020-04-30,04,"VAXJO OAS CAFE, VAXJO",-98,26295.7,NaN
3,2020-04-30,04,"PRESSBYRÅN 4025376, VÄXJÖ",-70,26393.7,NaN
4,2020-04-30,04,"kontaktlös LIDL 131/VEXJO OSTERLEDEN, VEXJO",-41.7,26463.7,NaN
...,...,...,...,...,...,...
225,2020-01-02,01,"WILLYS VÄXJÖ I11, VÄXJÖ",-1200.41,25103.3,NaN
226,2020-01-02,01,"SYSTEMBOLAGET VÄXJÖ, VÄXJÖ",-393,26303.7,NaN
227,2020-01-02,01,"WILLYS VÄXJÖ I11, VÄXJÖ",-23.8,26696.7,NaN
228,2020-01-02,01,"JULA AB, VÄXJÖ",-199,26720.5,NaN
229,2020-01-02,01,"BILTEMA SWEDEN VEXJO, VEXJO",-474.6,26919.5,NaN

In [46]:
# EXPORT

# fin.to_csv(path_or_buf = ('findata_'+str(fin['date'].min())+'_'+str(fin['date'].max())+'.csv'))
fin.to_csv('findata.csv')